- name: Install and start Docker on AlmaLinux 9
  hosts: SecondVM
  become: yes

  pre_tasks:
    - name: Remove podman-docker if installed
      ansible.builtin.dnf:
        name: podman-docker
        state: absent

    - name: Add Docker CE repo for RHEL8 (AlmaLinux9対応)
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/8/x86_64/stable/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install required system packages
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - git
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        allowerasing: true

  tasks:
    - name: Enable docker.socket
      ansible.builtin.systemd:
        name: docker.socket
        enabled: true
        state: started

    - name: Enable and start docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Add current user to docker group (optional)
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_user != "root"

    - name: Restart docker after group change
      ansible.builtin.systemd:
        name: docker
        state: restarted
      when: ansible_user != "root"

