---
- name: Deploy Flask App via Docker
  hosts: SecondVM
  become: yes

  vars:
    docker_image_name: flask-app
    docker_container_name: flask-container
    app_dir: /opt/flaskapp
    repo_url: "https://github.com/TestGitUser0/flask_setup.git"
    exposed_port: 80
    container_port: 5000

  pre_tasks:
    - name: Install required system packages
      dnf:
        name:
          - python3
          - python3-pip
          - docker
          - git
        state: present

    - name: Install Docker Python SDK
      pip:
        name: docker
        executable: pip3

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Ensure community.docker collection is installed
      ansible.builtin.shell: ansible-galaxy collection install community.docker
      args:
        creates: ~/.ansible/collections/ansible_collections/community/docker

  tasks:
    - name: Ensure app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory

    - name: Clone the Flask repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: test_docker
        force: yes

    - name: Build Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        build:
          path: "{{ app_dir }}"
        source: build

    - name: Remove old container if exists
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        state: absent
        force_kill: true

    - name: Run new Flask container
      community.docker.docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ docker_image_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ exposed_port }}:{{ container_port }}"

